### ISSUE TITLE
0.0.2 breaks separatorFinishedColor  

### ISSUE THREAD

**Issue by sonaye** [24ark/react-native-step-indicator#3]
I couldn't find any changelog that indicates a change in the api related to this property.

0.0.1
![kapture 2017-03-10 at 14 31 47](https://cloud.githubusercontent.com/assets/23000873/23794151/c31fb732-059f-11e7-96f1-2c3e436d87ef.gif)

0.0.2
![screen shot 2017-03-10 at 2 40 33 pm](https://cloud.githubusercontent.com/assets/23000873/23794147/bf82d4a6-059f-11e7-9738-2f377ec14dcb.png)

This occurs only when the step indicator is loaded with a certain step, but once it is animated to another step the coloring of the separator restores its correct behavior.

![kapture 2017-03-10 at 14 48 16](https://cloud.githubusercontent.com/assets/23000873/23794318/a2166dc8-05a0-11e7-9901-a0088c76e58b.gif)

Also, if you noticed, the separator extends beyond the last step, i haven't looked into this yet. I only upgraded to 0.0.2, no code changes.

```javascript
labels = [
  languageStore.get('job', 'hire'),
  languageStore.get('job', 'shareInfo'),
  languageStore.get('job', 'agreement'),
  languageStore.get('job', 'completion'),
  languageStore.get('job', 'feedback')
];

customStyles = {
  currentStepIndicatorLabelFontSize: 13,
  currentStepIndicatorSize: 30,
  currentStepLabelColor: colors.white,
  currentStepStrokeWidth: 3,
  labelColor: colors.white75,
  labelSize: 13,
  separatorFinishedColor: colors.yellow,
  separatorStrokeWidth: 2,
  separatorUnFinishedColor: colors.white,
  stepIndicatorCurrentColor: colors.white,
  stepIndicatorFinishedColor: colors.yellow,
  stepIndicatorLabelCurrentColor: colors.white,
  stepIndicatorLabelFinishedColor: colors.yellow,
  stepIndicatorLabelFontSize: 13,
  stepIndicatorLabelUnFinishedColor: colors.white,
  stepIndicatorSize: 25,
  stepIndicatorUnFinishedColor: colors.white,
  stepStrokeCurrentColor: colors.white,
  stepStrokeFinishedColor: colors.yellow,
  stepStrokeUnFinishedColor: colors.white,
  stepStrokeWidth: 3
};

// ..

<StepIndicator
  labels={this.labels}
  customStyles={this.customStyles}
  currentPosition={jobStore.job.step} // 0-5
/>
```

**Comment by 24ark** [comment]
@sonaye I have fixed these issues in v0.0.3

Thanks !

**Comment by sonaye** [comment]
@24ark Thanks for the effort. Hmm, the issue is still present after upgrading to 0.0.3. In addition, now there is a slight animation glitch whenever the state changes, I am using 0.0.1 in production and it's working perfectly, are there any new changes to the API that could cause this?

Step indicator when loaded with a certain value (same issue):
![simulator screen shot mar 18 2017 1 32 08 am](https://cloud.githubusercontent.com/assets/23000873/24065312/1421c676-0b7b-11e7-9a4c-f75e3b58d2f9.png)

New behavior:
![kapture 2017-03-18 at 1 32 01](https://cloud.githubusercontent.com/assets/23000873/24065374/79f452ca-0b7b-11e7-8006-4b6d902778f8.gif)

**Comment by 24ark** [comment]
@sonaye Thanks for reporting the issue. I have fixed the above mentioned issues in v0.0.4.

**Comment by sonaye** [comment]
I am afraid the issue is still present.
![screen shot 2017-03-30 at 10 10 31 pm](https://cloud.githubusercontent.com/assets/23000873/24521693/b5e54162-1595-11e7-9ab9-40e048ae1adb.png)

it only happens when the steps are completed and the indicator is preloaded with the value corresponding to completion (last step).

is my config correct?

```javascript
customStyles = {
    currentStepIndicatorLabelFontSize: 13,
    currentStepIndicatorSize: 30,
    currentStepLabelColor: colors.primary,
    currentStepStrokeWidth: 3,
    labelColor: colors.primary,
    labelSize: 13,
    separatorFinishedColor: colors.primary,
    separatorStrokeWidth: 2,
    separatorUnFinishedColor: colors.yellow,
    stepIndicatorCurrentColor: colors.yellow,
    stepIndicatorFinishedColor: colors.primary,
    stepIndicatorLabelCurrentColor: colors.yellow,
    stepIndicatorLabelFinishedColor: colors.primary,
    stepIndicatorLabelFontSize: 13,
    stepIndicatorLabelUnFinishedColor: colors.yellow,
    stepIndicatorSize: 25,
    stepIndicatorUnFinishedColor: colors.yellow,
    stepStrokeCurrentColor: colors.yellow,
    stepStrokeFinishedColor: colors.primary,
    stepStrokeUnFinishedColor: colors.yellow,
    stepStrokeWidth: 3
  };
```

**Comment by 24ark** [comment]
What is the `currentPage` prop value in the above case ? This wont work if  `currentPage > stepCount - 1`

**Comment by sonaye** [comment]
@24ark `currentPosition={5}`, i should start the count from zero is what you are saying? or only for the last step?

**Comment by 24ark** [comment]
Yes count starts from zero. In the above case `currentPosition={4}` for the last step.

**Comment by sonaye** [comment]
are you sure? this is how it looks with `currentPosition={4}`

![screen shot 2017-04-01 at 2 18 25 pm](https://cloud.githubusercontent.com/assets/23000873/24578301/9a3e6e78-16e6-11e7-901b-cc11ab9924f0.png)

**Comment by 24ark** [comment]
Fixed this in v0.0.5

**Comment by sonaye** [comment]
Fixed, but note that it was with count starting from 1 to 5, so only bumping from 0.0.1 to 0.0.5 solved the issue. Thanks!
